---
# tasks file for ubuntu-packages_install
- name: Update all packages
  apt:
    upgrade: yes
  become: yes

- name: Install EPEL packages
  apt:
    name: software-properties-common
    state: present
  become: yes

- name: Install Git
  apt:
    name: git
    state: present
  become: yes

- name: Install Pip3
  apt:
    name: python3-pip
    state: present
  become: yes

- name: Install python-telegrambot with Pip3
  pip:
    name: python-telegram-bot
    state: present
    executable: pip3
  become: yes

- name: Install python3-dotenv with pip3
  pip:
    name: python-dotenv
    state: present
    executable: pip3
  become: yes

- name: Install Flask with pip3
  pip:
    name: Flask
    state: present
    executable: pip3
  become: yes
