version: '3'

services:
  virus_scanner:
    image: canuski/clamavscanner:latest
    restart: unless-stopped
    volumes:
      - /root/Cloud-Sandbox/ansible/vars/telegram_vars.yml:/app/telegram_vars.yml
      - /root/Cloud-Sandbox/test_files:/app/test_files
    depends_on:
      - clamav

  clamav:
    image: mkodockx/docker-clamav:alpine
    restart: unless-stopped
    volumes:
    - /var/lib/clamav:/var/lib/clamav

  website:
    image: canuski/clamavwebsite:latest
    ports:
      - "5000:5000" 
    restart: unless-stopped
    volumes:
      - /root/Cloud-Sandbox/website:/app  
      - /root/Cloud-Sandbox/test_files:/app/test_files
    user: "100:101"


