---
- hosts: nodes
  become: yes
  vars_files:
    - ../vars/main.yml
    - ../vars/telegram_vars.yml
  roles:
    - set_hostname
  tasks:
    # Install for Rocky Linux 9
    # -------------------------------------------------
    - name: Setup project on Rocky Linux 9           #|
      include_role:                                  #|
        name: packages_install                       #|
      when: ansible_facts['distribution'] == 'Rocky' #|
    - include_role:                                  #|
        name: clamav_setup                           #|
      when: ansible_facts['distribution'] == 'Rocky' #|
    - include_role:                                  #|
        name: docker_setup                           #|
      when: ansible_facts['distribution'] == 'Rocky' #|
    - include_role:                                  #|
        name: docker-compose_setup                   #|
      when: ansible_facts['distribution'] == 'Rocky' #|
    - include_role:                                  #|
        name: firewall_setup                         #|
      when: ansible_facts['distribution'] == 'Rocky' #|
    # -------------------------------------------------


    # Install for Cent OS 7
    # --------------------------------------------------
    - name: Setup project on Cent OS 7                #|
      include_role:                                   #|
        name: centos-packages_install                 #|
      when: ansible_facts['distribution'] == 'CentOS' #|
    - include_role:                                   #|
        name: centos-clamav_setup                     #|
      when: ansible_facts['distribution'] == 'CentOS' #|
    - include_role:                                   #|
        name: centos-docker_setup                     #|
      when: ansible_facts['distribution'] == 'CentOS' #|
    - include_role:                                   #|
        name: centos-docker-compose_setup             #|
      when: ansible_facts['distribution'] == 'CentOS' #|
    - include_role:                                   #|
        name: centos-firewall_setup                   #|
      when: ansible_facts['distribution'] == 'CentOS' #|
    # --------------------------------------------------


    # Install for Ubuntu Server
    # --------------------------------------------------
    - name: Setup project on Ubuntu Server            #|
      include_role:                                   #|
        name: ubuntu-packages_install                 #|
      when: ansible_facts['distribution'] == 'Ubuntu' #|
    - include_role:                                   #|
        name: ubuntu-clamav_setup                     #|
      when: ansible_facts['distribution'] == 'Ubuntu' #|
    - include_role:                                   #|
        name: ubuntu-docker_setup                     #| 
      when: ansible_facts['distribution'] == 'Ubuntu' #|
    - include_role:                                   #|
        name: ubuntu-docker-compose_setup             #|
      when: ansible_facts['distribution'] == 'Ubuntu' #|
    - include_role:                                   #|
        name: ubuntu-firewall_setup                   #|
      when: ansible_facts['distribution'] == 'Ubuntu' #|
    # --------------------------------------------------

    - name: Reboot the system
      reboot: 