version: '3'

services:
  virus_scanner:
    image: scripts:latest
    volumes:
      - /home/s141479/Projects/Sandbox/Cloud-Sandbox/scripts/test_files/:/app/test_files
    depends_on:
      - clamav

  clamav:
    image: mkodockx/docker-clamav:alpine
    restart: unless-stopped
    volumes:
    - /var/lib/clamav:/var/lib/clamav
    command: ["sh", "-c", "freshclam && clamd"]
