---
# tasks file for packages_install
    - name: Update all packages
      dnf:
        name: '*'
        state: latest
      become: yes

    - name: Install EPEL packages
      command: sudo dnf -y install epel-release
      become: yes
      
    - name: Update package cache using dnf
      become: true
      dnf:
        name: '*'
        state: latest
 
    - name: Install Git
      dnf:
        name: git
        state: present
      become: yes

    - name: Install Pip3
      dnf:
        name: python3-pip
        state: present
      become: yes

    - name: Install python-telegrambot with Pip3
      command: pip3 install python-telegram-bot
      become: yes
  
    - name: Install python3-dotenv with pip3
      command: pip3 install python-dotenv
      become: yes

    - name: Install Flask with pip3
      command: pip3 install Flask
      become: yes
    
      